spring:
  application:
    name: movies-audit-logs
  datasource:
    driver-class-name: org.postgresql.Driver
    url: "jdbc:postgresql://localhost:11001/mydatabase"
    username: myuser
    password: secret
  jpa:
    hibernate:
      ddl-auto: update
server:
  port: 0

eureka:
  client:
    service-url:
      defaultZone: "http://localhost:8080/eureka"

axon:
  serializer:
    general: jackson
    events: jackson
    messages: jackson
